# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = { 
   kernelPackages = pkgs.linuxPackages_lqx;
   initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
   initrd.kernelModules = [ "amdgpu" ];
   kernelModules = [ "kvm-amd" ];
   extraModulePackages = [ ];
   blacklistedKernelModules = [ "nvidia-drm" "nvenc" "nouveau" ];
   kernelParams = [ 
    "video=DP-2:3440x1440@100" 
    "video=HDMI-1:1680x1050@59.85" 
    "nvme_load=YES" 
    "amdgpu.ppfeaturemask=0xfffd3fff" 
    "amdgpu.noretry=0"
    "amdgpu.lockup_timeout=1000"
    "amdgpu.gpu_recovery=1"
    "amdgpu.audio=0"
   ];
   extraModprobeConfig = ''
     options zfs l2arc_noprefetch=0 l2arc_write_boost=33554432 l2arc_write_max=16777216 zfs_arc_max=2147483648
   '';  
   loader.grub = {
    enable = true;
    zfsSupport = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    mirroredBoots = [
      { devices = [ "nodev"]; path = "/boot"; }
      { devices = [ "nodev"]; path = "/boot-mirror"; }
    ];
   };
 };

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ad3197da-7f26-4a67-82da-79795351ef0a";
      fsType = "ext4";
    };

  fileSystems."/home/kabi/Games" =
    { device = "/dev/disk/by-uuid/3e981248-86ee-46e3-beb5-5efa495be574";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/68BA-B88A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/boot-mirror" =
    { device = "/dev/disk/by-uuid/68BC-203A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };


  swapDevices = [ 
    { 
     device = "/dev/disk/by-uuid/d3ca6e11-6d90-4196-a7c8-5b4d2b0bd6c6";
    }
    {
     device = "/dev/disk/by-uuid/64cdec3c-be0d-4c37-9e36-0bf403a953b4";
    }
  ];

  services.zfs.autoSnapshot.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
